[[headers]]
  for = "/*"
  [headers.values]
    # Hugo uses inline styling for syntax highlighting,
    # disabling CSP until we figure out a way to get it in a file
    # Content-Security-Policy = "default-src 'self'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"