[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "style-src 'sha512-NzRiMWJlMzExMjFkZWI0MmQ5YzYzZDQ2NjViZTU4NGI5YjhjODJkZWU3YWFmZjRkNmI5ZmFiMzI5ODY3MTMyNTkxMTIyYjRmOWY0OGJiZWI3ZjZmNWQwMmUwMWUzNDJkYmZhMGE3MzkwMDJmNzM4ZmE1YTk5NzcxNzg2MzhhN2Y='; default-src 'self'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "autoplay 'none'; camera 'none'; geolocation 'none'; microphone 'none'; midi 'none'; payment 'none'; usb 'none'"
